[2014-03-07 09:30:59] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Controllers\Admin\Post' not found' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:517 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-03-07 10:32:53] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Controllers\Admin\Mainvoicestatus' not found' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:67 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-03-07 10:34:20] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Controllers\Admin\Mainvoicestatus' not found' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:67 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-03-07 10:34:51] log.ERROR: exception 'ErrorException' with message 'Undefined index: draft' in /var/www/arp_dev/app/storage/views/bb246097065f941c3fdcdc78accd32c0:126 Stack trace: #0 /var/www/arp_dev/app/storage/views/bb246097065f941c3fdcdc78accd32c0(126): Illuminate\Exception\Handler->handleError(8, 'Undefined index...', '/var/www/arp_de...', 126, Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(38): include('/var/www/arp_de...') #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/arp_de...', Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/View.php(100): Illuminate\View\Engines\CompilerEngine->get('/var/www/arp_de...', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/View.php(81): Illuminate\View\View->getContents() #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Http/Response.php(70): Illuminate\View\View->render() #6 /var/www/arp_dev/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(141): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1414): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getIndex', Object(Illuminate\View\View)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #18 {main} [] []
[2014-03-07 10:37:46] log.ERROR: exception 'ErrorException' with message 'Undefined index: draft' in /var/www/arp_dev/app/storage/views/bb246097065f941c3fdcdc78accd32c0:126 Stack trace: #0 /var/www/arp_dev/app/storage/views/bb246097065f941c3fdcdc78accd32c0(126): Illuminate\Exception\Handler->handleError(8, 'Undefined index...', '/var/www/arp_de...', 126, Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(38): include('/var/www/arp_de...') #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/arp_de...', Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/View.php(100): Illuminate\View\Engines\CompilerEngine->get('/var/www/arp_de...', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/View.php(81): Illuminate\View\View->getContents() #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Http/Response.php(70): Illuminate\View\View->render() #6 /var/www/arp_dev/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(141): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1414): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getIndex', Object(Illuminate\View\View)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #18 {main} [] []
[2014-03-07 10:37:46] log.ERROR: exception 'ErrorException' with message 'Undefined index: draft' in /var/www/arp_dev/app/storage/views/bb246097065f941c3fdcdc78accd32c0:126 Stack trace: #0 /var/www/arp_dev/app/storage/views/bb246097065f941c3fdcdc78accd32c0(126): Illuminate\Exception\Handler->handleError(8, 'Undefined index...', '/var/www/arp_de...', 126, Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(38): include('/var/www/arp_de...') #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/arp_de...', Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/View.php(100): Illuminate\View\Engines\CompilerEngine->get('/var/www/arp_de...', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/View.php(81): Illuminate\View\View->getContents() #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Http/Response.php(70): Illuminate\View\View->render() #6 /var/www/arp_dev/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(141): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1414): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getIndex', Object(Illuminate\View\View)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #18 {main} [] []
[2014-03-07 10:37:46] log.ERROR: exception 'ErrorException' with message 'Undefined index: draft' in /var/www/arp_dev/app/storage/views/bb246097065f941c3fdcdc78accd32c0:126 Stack trace: #0 /var/www/arp_dev/app/storage/views/bb246097065f941c3fdcdc78accd32c0(126): Illuminate\Exception\Handler->handleError(8, 'Undefined index...', '/var/www/arp_de...', 126, Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(38): include('/var/www/arp_de...') #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/arp_de...', Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/View.php(100): Illuminate\View\Engines\CompilerEngine->get('/var/www/arp_de...', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/View.php(81): Illuminate\View\View->getContents() #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Http/Response.php(70): Illuminate\View\View->render() #6 /var/www/arp_dev/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(141): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1414): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getIndex', Object(Illuminate\View\View)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #18 {main} [] []
[2014-03-07 10:38:56] log.ERROR: exception 'ErrorException' with message 'Undefined index: draft' in /var/www/arp_dev/app/storage/views/bb246097065f941c3fdcdc78accd32c0:127 Stack trace: #0 /var/www/arp_dev/app/storage/views/bb246097065f941c3fdcdc78accd32c0(127): Illuminate\Exception\Handler->handleError(8, 'Undefined index...', '/var/www/arp_de...', 127, Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(38): include('/var/www/arp_de...') #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/arp_de...', Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/View.php(100): Illuminate\View\Engines\CompilerEngine->get('/var/www/arp_de...', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/View.php(81): Illuminate\View\View->getContents() #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Http/Response.php(70): Illuminate\View\View->render() #6 /var/www/arp_dev/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(141): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1414): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getIndex', Object(Illuminate\View\View)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #18 {main} [] []
[2014-03-07 10:39:57] log.ERROR: exception 'ErrorException' with message 'Undefined property: Illuminate\Database\Eloquent\Builder::$status' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:70 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(70): Illuminate\Exception\Handler->handleError(8, 'Undefined prope...', '/var/www/arp_de...', 70, Array) #1 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2014-03-07 10:40:35] log.ERROR: exception 'ErrorException' with message 'Undefined property: Illuminate\Database\Query\Builder::$status' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:71 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(71): Illuminate\Exception\Handler->handleError(8, 'Undefined prope...', '/var/www/arp_de...', 71, Array) #1 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2014-03-07 10:41:09] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:71 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(71): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/arp_de...', 71, Array) #1 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2014-03-07 10:41:30] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:71 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(71): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/arp_de...', 71, Array) #1 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2014-03-07 11:14:54] log.ERROR: exception 'ErrorException' with message 'Undefined variable: numtransactions' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:410 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(410): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/var/www/arp_de...', 410, Array) #1 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(153): Controllers\Admin\MainvoiceController->getRedemptions(6, '2014-03-07', '2014-03-17') #2 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(64): Controllers\Admin\MainvoiceController->generate() #3 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #13 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #14 {main} [] []
[2014-03-07 11:23:33] log.ERROR: exception 'ErrorException' with message 'Undefined index: amountchargebacks' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:166 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(166): Illuminate\Exception\Handler->handleError(8, 'Undefined index...', '/var/www/arp_de...', 166, Array) #1 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(64): Controllers\Admin\MainvoiceController->generate() #2 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2014-03-07 11:24:13] log.ERROR: exception 'ErrorException' with message 'Undefined variable: chb_amount' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:168 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(168): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/var/www/arp_de...', 168, Array) #1 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(64): Controllers\Admin\MainvoiceController->generate() #2 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2014-03-07 11:50:35] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/arp_dev/app/storage/views/2d8971310e59d66b3c8ffc54892f57e2:60 Stack trace: #0 /var/www/arp_dev/app/storage/views/2d8971310e59d66b3c8ffc54892f57e2(60): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/arp_de...', 60, Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(38): include('/var/www/arp_de...') #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/arp_de...', Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/View.php(100): Illuminate\View\Engines\CompilerEngine->get('/var/www/arp_de...', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/View.php(81): Illuminate\View\View->getContents() #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Http/Response.php(70): Illuminate\View\View->render() #6 /var/www/arp_dev/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(141): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1414): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getShow', Object(Illuminate\View\View)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getShow', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('1009') #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #18 {main} [] []
[2014-03-07 13:50:34] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Controllers\Admin\Mainvoicerows' not found' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:248 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-03-07 13:50:50] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Database\Eloquent\Collection::save()' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:273 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-03-07 14:09:56] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:218 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(218): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/arp_de...', 218, Array) #1 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(65): Controllers\Admin\MainvoiceController->generate() #2 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2014-03-07 14:11:19] log.ERROR: exception 'ErrorException' with message 'Array to string conversion' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:353 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleError(8, 'Array to string...', '/var/www/arp_de...', 353, Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(353): PDOStatement->execute(Array) #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\PostgresConnection), 'update "mainvoi...', Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(356): Illuminate\Database\Connection->run('update "mainvoi...', Array, Object(Closure)) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(301): Illuminate\Database\Connection->affectingStatement('update "mainvoi...', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1459): Illuminate\Database\Connection->update('update "mainvoi...', Array) #6 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(245): Illuminate\Database\Query\Builder->update(Array) #7 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(65): Controllers\Admin\MainvoiceController->generate() #8 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #12 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #18 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #19 {main} Next exception 'Exception' with message 'Array to string conversion (SQL: update "mainvoicerows" set "0" = ?, "1" = ?, "2" = ?, "3" = ? where "mainvoice_id" = ?) (Bindings: array (   0 =>    array (     'mainvoice_id' => 1,     'description' => 'processed_amount',     'user_id' => 1,     'amount' => 600,   ),   1 =>    array (     'mainvoice_id' => 1,     'description' => 'refunded_amount',     'user_id' => 1,     'amount' => 25,   ),   2 =>    array (     'mainvoice_id' => 1,     'description' => 'chargebacked_amount',     'user_id' => 1,     'amount' => 0,   ),   3 =>    array (     'mainvoice_id' => 1,     'description' => 'payable_sum',     'user_id' => 1,     'amount' => 575,   ),   4 => 1000, ))' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:556 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(ErrorException), 'update "mainvoi...', Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(356): Illuminate\Database\Connection->run('update "mainvoi...', Array, Object(Closure)) #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(301): Illuminate\Database\Connection->affectingStatement('update "mainvoi...', Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1459): Illuminate\Database\Connection->update('update "mainvoi...', Array) #4 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(245): Illuminate\Database\Query\Builder->update(Array) #5 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(65): Controllers\Admin\MainvoiceController->generate() #6 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #10 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #16 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #17 {main} [] []
[2014-03-07 14:43:10] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'public' (T_PUBLIC)' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:324 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-03-07 14:44:42] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'public' (T_PUBLIC)' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:324 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-03-07 14:47:50] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'public' (T_PUBLIC)' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:324 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-03-07 14:47:52] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'public' (T_PUBLIC)' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:324 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-03-07 14:47:53] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'public' (T_PUBLIC)' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:324 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-03-07 14:47:53] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'public' (T_PUBLIC)' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:324 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-03-07 14:47:53] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'public' (T_PUBLIC)' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:324 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-03-07 14:47:53] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'public' (T_PUBLIC)' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:324 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-03-07 14:47:53] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'public' (T_PUBLIC)' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:324 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-03-07 14:47:53] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'public' (T_PUBLIC)' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:324 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-03-07 14:47:53] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'public' (T_PUBLIC)' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:324 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-03-07 14:47:53] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'public' (T_PUBLIC)' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:324 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-03-07 14:47:53] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'public' (T_PUBLIC)' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:324 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-03-07 14:47:53] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'public' (T_PUBLIC)' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:324 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-03-07 14:47:53] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'public' (T_PUBLIC)' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:324 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-03-07 14:47:53] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'public' (T_PUBLIC)' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:324 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-03-07 14:47:53] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'public' (T_PUBLIC)' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:324 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-03-07 14:47:53] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'public' (T_PUBLIC)' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:324 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-03-07 14:47:53] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'public' (T_PUBLIC)' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:324 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-03-07 14:48:02] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'public' (T_PUBLIC)' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:324 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-03-07 14:51:57] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'public' (T_PUBLIC)' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:316 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-03-07 14:54:09] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'public' (T_PUBLIC)' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:316 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-03-07 15:30:22] log.ERROR: exception 'ErrorException' with message 'Undefined variable: check_id' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:228 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(228): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/var/www/arp_de...', 228, Array) #1 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(65): Controllers\Admin\MainvoiceController->generate() #2 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2014-03-07 15:31:19] log.ERROR: exception 'ErrorException' with message 'Undefined variable: check_id' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:233 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(233): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/var/www/arp_de...', 233, Array) #1 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(65): Controllers\Admin\MainvoiceController->generate() #2 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2014-03-07 15:31:41] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42703]: Undefined column: 7 ERROR:  column "mainvoice_id" does not exist LINE 1: ...nt" = $1, "user_id" = $2, "updated_at" = $3 where "mainvoice...                                                              ^' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:353 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(353): PDOStatement->execute(Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\PostgresConnection), 'update "mainvoi...', Array) #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(356): Illuminate\Database\Connection->run('update "mainvoi...', Array, Object(Closure)) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(301): Illuminate\Database\Connection->affectingStatement('update "mainvoi...', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1459): Illuminate\Database\Connection->update('update "mainvoi...', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(277): Illuminate\Database\Query\Builder->update(Array) #6 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(238): Illuminate\Database\Eloquent\Builder->update(Array) #7 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(65): Controllers\Admin\MainvoiceController->generate() #8 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #12 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #18 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #19 {main} Next exception 'Exception' with message 'SQLSTATE[42703]: Undefined column: 7 ERROR:  column "mainvoice_id" does not exist LINE 1: ...nt" = $1, "user_id" = $2, "updated_at" = $3 where "mainvoice...                                                              ^ (SQL: update "mainvoice" set "amount" = ?, "user_id" = ?, "updated_at" = ? where "mainvoice_id" = ? and "description" = ?) (Bindings: array (   0 => NULL,   1 => 1,   2 => '2014-03-07 15:31:41',   3 => 1000,   4 => 'processed_amount', ))' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:556 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'update "mainvoi...', Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(356): Illuminate\Database\Connection->run('update "mainvoi...', Array, Object(Closure)) #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(301): Illuminate\Database\Connection->affectingStatement('update "mainvoi...', Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1459): Illuminate\Database\Connection->update('update "mainvoi...', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(277): Illuminate\Database\Query\Builder->update(Array) #5 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(238): Illuminate\Database\Eloquent\Builder->update(Array) #6 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(65): Controllers\Admin\MainvoiceController->generate() #7 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #18 {main} [] []
[2014-03-07 15:33:31] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42703]: Undefined column: 7 ERROR:  column "mainvoice_id" does not exist LINE 1: ...nt" = $1, "user_id" = $2, "updated_at" = $3 where "mainvoice...                                                              ^' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:353 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(353): PDOStatement->execute(Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\PostgresConnection), 'update "mainvoi...', Array) #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(356): Illuminate\Database\Connection->run('update "mainvoi...', Array, Object(Closure)) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(301): Illuminate\Database\Connection->affectingStatement('update "mainvoi...', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1459): Illuminate\Database\Connection->update('update "mainvoi...', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(277): Illuminate\Database\Query\Builder->update(Array) #6 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(238): Illuminate\Database\Eloquent\Builder->update(Array) #7 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(65): Controllers\Admin\MainvoiceController->generate() #8 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #12 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #18 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #19 {main} Next exception 'Exception' with message 'SQLSTATE[42703]: Undefined column: 7 ERROR:  column "mainvoice_id" does not exist LINE 1: ...nt" = $1, "user_id" = $2, "updated_at" = $3 where "mainvoice...                                                              ^ (SQL: update "mainvoice" set "amount" = ?, "user_id" = ?, "updated_at" = ? where "mainvoice_id" = ? and "description" = ?) (Bindings: array (   0 => NULL,   1 => 1,   2 => '2014-03-07 15:33:31',   3 => 1000,   4 => 'processed_amount', ))' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:556 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'update "mainvoi...', Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(356): Illuminate\Database\Connection->run('update "mainvoi...', Array, Object(Closure)) #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(301): Illuminate\Database\Connection->affectingStatement('update "mainvoi...', Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1459): Illuminate\Database\Connection->update('update "mainvoi...', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(277): Illuminate\Database\Query\Builder->update(Array) #5 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(238): Illuminate\Database\Eloquent\Builder->update(Array) #6 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(65): Controllers\Admin\MainvoiceController->generate() #7 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #18 {main} [] []
[2014-03-07 15:33:44] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42703]: Undefined column: 7 ERROR:  column "mainvoice_id" does not exist LINE 1: ...nt" = $1, "user_id" = $2, "updated_at" = $3 where "mainvoice...                                                              ^' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:353 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(353): PDOStatement->execute(Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\PostgresConnection), 'update "mainvoi...', Array) #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(356): Illuminate\Database\Connection->run('update "mainvoi...', Array, Object(Closure)) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(301): Illuminate\Database\Connection->affectingStatement('update "mainvoi...', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1459): Illuminate\Database\Connection->update('update "mainvoi...', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(277): Illuminate\Database\Query\Builder->update(Array) #6 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(238): Illuminate\Database\Eloquent\Builder->update(Array) #7 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(65): Controllers\Admin\MainvoiceController->generate() #8 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #12 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #18 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #19 {main} Next exception 'Exception' with message 'SQLSTATE[42703]: Undefined column: 7 ERROR:  column "mainvoice_id" does not exist LINE 1: ...nt" = $1, "user_id" = $2, "updated_at" = $3 where "mainvoice...                                                              ^ (SQL: update "mainvoice" set "amount" = ?, "user_id" = ?, "updated_at" = ? where "mainvoice_id" = ? and "description" = ?) (Bindings: array (   0 => NULL,   1 => 1,   2 => '2014-03-07 15:33:44',   3 => 1000,   4 => 'processed_amount', ))' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:556 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'update "mainvoi...', Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(356): Illuminate\Database\Connection->run('update "mainvoi...', Array, Object(Closure)) #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(301): Illuminate\Database\Connection->affectingStatement('update "mainvoi...', Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1459): Illuminate\Database\Connection->update('update "mainvoi...', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(277): Illuminate\Database\Query\Builder->update(Array) #5 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(238): Illuminate\Database\Eloquent\Builder->update(Array) #6 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(65): Controllers\Admin\MainvoiceController->generate() #7 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #18 {main} [] []
[2014-03-07 15:38:24] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42703]: Undefined column: 7 ERROR:  column "mainvoice_id" does not exist LINE 1: ...nt" = $1, "user_id" = $2, "updated_at" = $3 where "mainvoice...                                                              ^' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:353 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(353): PDOStatement->execute(Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\PostgresConnection), 'update "mainvoi...', Array) #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(356): Illuminate\Database\Connection->run('update "mainvoi...', Array, Object(Closure)) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(301): Illuminate\Database\Connection->affectingStatement('update "mainvoi...', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1459): Illuminate\Database\Connection->update('update "mainvoi...', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(277): Illuminate\Database\Query\Builder->update(Array) #6 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(239): Illuminate\Database\Eloquent\Builder->update(Array) #7 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(65): Controllers\Admin\MainvoiceController->generate() #8 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #12 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #18 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #19 {main} Next exception 'Exception' with message 'SQLSTATE[42703]: Undefined column: 7 ERROR:  column "mainvoice_id" does not exist LINE 1: ...nt" = $1, "user_id" = $2, "updated_at" = $3 where "mainvoice...                                                              ^ (SQL: update "mainvoice" set "amount" = ?, "user_id" = ?, "updated_at" = ? where "mainvoice_id" = ? and "description" = ?) (Bindings: array (   0 => NULL,   1 => 1,   2 => '2014-03-07 15:38:24',   3 => 1000,   4 => 'processed_amount', ))' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:556 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'update "mainvoi...', Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(356): Illuminate\Database\Connection->run('update "mainvoi...', Array, Object(Closure)) #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(301): Illuminate\Database\Connection->affectingStatement('update "mainvoi...', Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1459): Illuminate\Database\Connection->update('update "mainvoi...', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(277): Illuminate\Database\Query\Builder->update(Array) #5 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(239): Illuminate\Database\Eloquent\Builder->update(Array) #6 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(65): Controllers\Admin\MainvoiceController->generate() #7 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #18 {main} [] []
[2014-03-07 15:39:23] log.ERROR: exception 'ErrorException' with message 'Undefined variable: inverows' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:237 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(237): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/var/www/arp_de...', 237, Array) #1 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(65): Controllers\Admin\MainvoiceController->generate() #2 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2014-03-07 15:39:32] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42703]: Undefined column: 7 ERROR:  column "mainvoice_id" does not exist LINE 1: ...nt" = $1, "user_id" = $2, "updated_at" = $3 where "mainvoice...                                                              ^' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:353 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(353): PDOStatement->execute(Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\PostgresConnection), 'update "mainvoi...', Array) #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(356): Illuminate\Database\Connection->run('update "mainvoi...', Array, Object(Closure)) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(301): Illuminate\Database\Connection->affectingStatement('update "mainvoi...', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1459): Illuminate\Database\Connection->update('update "mainvoi...', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(277): Illuminate\Database\Query\Builder->update(Array) #6 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(239): Illuminate\Database\Eloquent\Builder->update(Array) #7 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(65): Controllers\Admin\MainvoiceController->generate() #8 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #12 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #18 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #19 {main} Next exception 'Exception' with message 'SQLSTATE[42703]: Undefined column: 7 ERROR:  column "mainvoice_id" does not exist LINE 1: ...nt" = $1, "user_id" = $2, "updated_at" = $3 where "mainvoice...                                                              ^ (SQL: update "mainvoice" set "amount" = ?, "user_id" = ?, "updated_at" = ? where "mainvoice_id" = ? and "description" = ?) (Bindings: array (   0 => 230,   1 => 1,   2 => '2014-03-07 15:39:32',   3 => 1000,   4 => 'processed_amount', ))' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:556 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'update "mainvoi...', Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(356): Illuminate\Database\Connection->run('update "mainvoi...', Array, Object(Closure)) #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(301): Illuminate\Database\Connection->affectingStatement('update "mainvoi...', Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1459): Illuminate\Database\Connection->update('update "mainvoi...', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(277): Illuminate\Database\Query\Builder->update(Array) #5 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(239): Illuminate\Database\Eloquent\Builder->update(Array) #6 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(65): Controllers\Admin\MainvoiceController->generate() #7 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #18 {main} [] []
[2014-03-07 15:40:07] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42703]: Undefined column: 7 ERROR:  column "mainvoice_id" does not exist LINE 1: ...nt" = $1, "user_id" = $2, "updated_at" = $3 where "mainvoice...                                                              ^' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:353 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(353): PDOStatement->execute(Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\PostgresConnection), 'update "mainvoi...', Array) #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(356): Illuminate\Database\Connection->run('update "mainvoi...', Array, Object(Closure)) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(301): Illuminate\Database\Connection->affectingStatement('update "mainvoi...', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1459): Illuminate\Database\Connection->update('update "mainvoi...', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(277): Illuminate\Database\Query\Builder->update(Array) #6 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(239): Illuminate\Database\Eloquent\Builder->update(Array) #7 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(65): Controllers\Admin\MainvoiceController->generate() #8 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #12 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #18 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #19 {main} Next exception 'Exception' with message 'SQLSTATE[42703]: Undefined column: 7 ERROR:  column "mainvoice_id" does not exist LINE 1: ...nt" = $1, "user_id" = $2, "updated_at" = $3 where "mainvoice...                                                              ^ (SQL: update "mainvoice" set "amount" = ?, "user_id" = ?, "updated_at" = ? where "mainvoice_id" = ? and "description" = ?) (Bindings: array (   0 => 230,   1 => 1,   2 => '2014-03-07 15:40:07',   3 => 1000,   4 => 'processed_amount', ))' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:556 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'update "mainvoi...', Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(356): Illuminate\Database\Connection->run('update "mainvoi...', Array, Object(Closure)) #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(301): Illuminate\Database\Connection->affectingStatement('update "mainvoi...', Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1459): Illuminate\Database\Connection->update('update "mainvoi...', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(277): Illuminate\Database\Query\Builder->update(Array) #5 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(239): Illuminate\Database\Eloquent\Builder->update(Array) #6 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(65): Controllers\Admin\MainvoiceController->generate() #7 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #18 {main} [] []
[2014-03-07 15:54:31] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/arp_dev/app/storage/views/bb246097065f941c3fdcdc78accd32c0:127 Stack trace: #0 /var/www/arp_dev/app/storage/views/bb246097065f941c3fdcdc78accd32c0(127): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/arp_de...', 127, Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(38): include('/var/www/arp_de...') #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/arp_de...', Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/View.php(100): Illuminate\View\Engines\CompilerEngine->get('/var/www/arp_de...', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/View.php(81): Illuminate\View\View->getContents() #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Http/Response.php(70): Illuminate\View\View->render() #6 /var/www/arp_dev/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(141): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1414): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getIndex', Object(Illuminate\View\View)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #18 {main} [] []
[2014-03-07 16:14:21] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '$invoicerow' (T_VARIABLE)' in /var/www/arp_dev/app/storage/views/2d8971310e59d66b3c8ffc54892f57e2:230 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-03-07 16:14:36] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ';'' in /var/www/arp_dev/app/storage/views/2d8971310e59d66b3c8ffc54892f57e2:230 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
